apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-petclinic
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: st251/petclinic       
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds           
    argocd-image-updater.argoproj.io/git-branch: main                                          
    argocd-image-updater.argoproj.io/myalias.force-update: "true"
spec:
  project: default

  source:
    repoURL: https://github.com/YuriiDiduk/ArgoCD-pet-config.git
    targetRevision: HEAD
    path: prod
  destination: 
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
